	ECE178_nios_20_1 u0 (
		.clk_clk                                     (<connected-to-clk_clk>),                                     //                  clk.clk
		.hex0_3_export                               (<connected-to-hex0_3_export>),                               //               hex0_3.export
		.hex4_7_export                               (<connected-to-hex4_7_export>),                               //               hex4_7.export
		.key_export                                  (<connected-to-key_export>),                                  //                  key.export
		.ledg_export                                 (<connected-to-ledg_export>),                                 //                 ledg.export
		.ledr_export                                 (<connected-to-ledr_export>),                                 //                 ledr.export
		.reset_reset                                 (<connected-to-reset_reset>),                                 //                reset.reset
		.sdram_addr                                  (<connected-to-sdram_addr>),                                  //                sdram.addr
		.sdram_ba                                    (<connected-to-sdram_ba>),                                    //                     .ba
		.sdram_cas_n                                 (<connected-to-sdram_cas_n>),                                 //                     .cas_n
		.sdram_cke                                   (<connected-to-sdram_cke>),                                   //                     .cke
		.sdram_cs_n                                  (<connected-to-sdram_cs_n>),                                  //                     .cs_n
		.sdram_dq                                    (<connected-to-sdram_dq>),                                    //                     .dq
		.sdram_dqm                                   (<connected-to-sdram_dqm>),                                   //                     .dqm
		.sdram_ras_n                                 (<connected-to-sdram_ras_n>),                                 //                     .ras_n
		.sdram_we_n                                  (<connected-to-sdram_we_n>),                                  //                     .we_n
		.sdram_clk_clk                               (<connected-to-sdram_clk_clk>),                               //            sdram_clk.clk
		.switches0_17_export                         (<connected-to-switches0_17_export>),                         //         switches0_17.export
		.slave_user_interface_user_dataout_0_export  (<connected-to-slave_user_interface_user_dataout_0_export>),  // slave_user_interface.user_dataout_0_export
		.slave_user_interface_user_dataout_1_export  (<connected-to-slave_user_interface_user_dataout_1_export>),  //                     .user_dataout_1_export
		.slave_user_interface_user_dataout_2_export  (<connected-to-slave_user_interface_user_dataout_2_export>),  //                     .user_dataout_2_export
		.slave_user_interface_user_dataout_3_export  (<connected-to-slave_user_interface_user_dataout_3_export>),  //                     .user_dataout_3_export
		.slave_user_interface_user_dataout_4_export  (<connected-to-slave_user_interface_user_dataout_4_export>),  //                     .user_dataout_4_export
		.slave_user_interface_user_dataout_5_export  (<connected-to-slave_user_interface_user_dataout_5_export>),  //                     .user_dataout_5_export
		.slave_user_interface_user_dataout_6_export  (<connected-to-slave_user_interface_user_dataout_6_export>),  //                     .user_dataout_6_export
		.slave_user_interface_user_dataout_7_export  (<connected-to-slave_user_interface_user_dataout_7_export>),  //                     .user_dataout_7_export
		.slave_user_interface_user_dataout_8_export  (<connected-to-slave_user_interface_user_dataout_8_export>),  //                     .user_dataout_8_export
		.slave_user_interface_user_dataout_9_export  (<connected-to-slave_user_interface_user_dataout_9_export>),  //                     .user_dataout_9_export
		.slave_user_interface_user_dataout_10_export (<connected-to-slave_user_interface_user_dataout_10_export>), //                     .user_dataout_10_export
		.slave_user_interface_user_dataout_11_export (<connected-to-slave_user_interface_user_dataout_11_export>), //                     .user_dataout_11_export
		.slave_user_interface_user_dataout_12_export (<connected-to-slave_user_interface_user_dataout_12_export>), //                     .user_dataout_12_export
		.slave_user_interface_user_dataout_13_export (<connected-to-slave_user_interface_user_dataout_13_export>), //                     .user_dataout_13_export
		.slave_user_interface_user_dataout_14_export (<connected-to-slave_user_interface_user_dataout_14_export>), //                     .user_dataout_14_export
		.slave_user_interface_user_dataout_15_export (<connected-to-slave_user_interface_user_dataout_15_export>), //                     .user_dataout_15_export
		.slave_user_interface_user_datain_0_export   (<connected-to-slave_user_interface_user_datain_0_export>),   //                     .user_datain_0_export
		.slave_user_interface_user_datain_1_export   (<connected-to-slave_user_interface_user_datain_1_export>),   //                     .user_datain_1_export
		.slave_user_interface_user_datain_2_export   (<connected-to-slave_user_interface_user_datain_2_export>),   //                     .user_datain_2_export
		.slave_user_interface_user_datain_3_export   (<connected-to-slave_user_interface_user_datain_3_export>),   //                     .user_datain_3_export
		.slave_user_interface_user_datain_4_export   (<connected-to-slave_user_interface_user_datain_4_export>),   //                     .user_datain_4_export
		.slave_user_interface_user_datain_5_export   (<connected-to-slave_user_interface_user_datain_5_export>),   //                     .user_datain_5_export
		.slave_user_interface_user_datain_6_export   (<connected-to-slave_user_interface_user_datain_6_export>),   //                     .user_datain_6_export
		.slave_user_interface_user_datain_7_export   (<connected-to-slave_user_interface_user_datain_7_export>),   //                     .user_datain_7_export
		.slave_user_interface_user_datain_8_export   (<connected-to-slave_user_interface_user_datain_8_export>),   //                     .user_datain_8_export
		.slave_user_interface_user_datain_9_export   (<connected-to-slave_user_interface_user_datain_9_export>),   //                     .user_datain_9_export
		.slave_user_interface_user_datain_10_export  (<connected-to-slave_user_interface_user_datain_10_export>),  //                     .user_datain_10_export
		.slave_user_interface_user_datain_11_export  (<connected-to-slave_user_interface_user_datain_11_export>),  //                     .user_datain_11_export
		.slave_user_interface_user_datain_12_export  (<connected-to-slave_user_interface_user_datain_12_export>),  //                     .user_datain_12_export
		.slave_user_interface_user_datain_13_export  (<connected-to-slave_user_interface_user_datain_13_export>),  //                     .user_datain_13_export
		.slave_user_interface_user_datain_14_export  (<connected-to-slave_user_interface_user_datain_14_export>),  //                     .user_datain_14_export
		.slave_user_interface_user_datain_15_export  (<connected-to-slave_user_interface_user_datain_15_export>),  //                     .user_datain_15_export
		.slave_user_interface_user_write_export      (<connected-to-slave_user_interface_user_write_export>),      //                     .user_write_export
		.slave_user_interface_user_read_export       (<connected-to-slave_user_interface_user_read_export>),       //                     .user_read_export
		.slave_user_interface_user_chipselect_export (<connected-to-slave_user_interface_user_chipselect_export>)  //                     .user_chipselect_export
	);

