	ECE178_nios_20_1 u0 (
		.clk_clk                                            (<connected-to-clk_clk>),                                            //                                         clk.clk
		.gpio_external_connection_export                    (<connected-to-gpio_external_connection_export>),                    //                    gpio_external_connection.export
		.hex0_3_export                                      (<connected-to-hex0_3_export>),                                      //                                      hex0_3.export
		.hex4_7_export                                      (<connected-to-hex4_7_export>),                                      //                                      hex4_7.export
		.key_export                                         (<connected-to-key_export>),                                         //                                         key.export
		.ledg_export                                        (<connected-to-ledg_export>),                                        //                                        ledg.export
		.ledr_export                                        (<connected-to-ledr_export>),                                        //                                        ledr.export
		.reset_reset                                        (<connected-to-reset_reset>),                                        //                                       reset.reset
		.sbus_decoder_channel_0_external_connection_export  (<connected-to-sbus_decoder_channel_0_external_connection_export>),  //  sbus_decoder_channel_0_external_connection.export
		.sbus_decoder_channel_10_external_connection_export (<connected-to-sbus_decoder_channel_10_external_connection_export>), // sbus_decoder_channel_10_external_connection.export
		.sbus_decoder_channel_11_external_connection_export (<connected-to-sbus_decoder_channel_11_external_connection_export>), // sbus_decoder_channel_11_external_connection.export
		.sbus_decoder_channel_12_external_connection_export (<connected-to-sbus_decoder_channel_12_external_connection_export>), // sbus_decoder_channel_12_external_connection.export
		.sbus_decoder_channel_13_external_connection_export (<connected-to-sbus_decoder_channel_13_external_connection_export>), // sbus_decoder_channel_13_external_connection.export
		.sbus_decoder_channel_14_external_connection_export (<connected-to-sbus_decoder_channel_14_external_connection_export>), // sbus_decoder_channel_14_external_connection.export
		.sbus_decoder_channel_15_external_connection_export (<connected-to-sbus_decoder_channel_15_external_connection_export>), // sbus_decoder_channel_15_external_connection.export
		.sbus_decoder_channel_1_external_connection_export  (<connected-to-sbus_decoder_channel_1_external_connection_export>),  //  sbus_decoder_channel_1_external_connection.export
		.sbus_decoder_channel_2_external_connection_export  (<connected-to-sbus_decoder_channel_2_external_connection_export>),  //  sbus_decoder_channel_2_external_connection.export
		.sbus_decoder_channel_3_external_connection_export  (<connected-to-sbus_decoder_channel_3_external_connection_export>),  //  sbus_decoder_channel_3_external_connection.export
		.sbus_decoder_channel_4_external_connection_export  (<connected-to-sbus_decoder_channel_4_external_connection_export>),  //  sbus_decoder_channel_4_external_connection.export
		.sbus_decoder_channel_5_external_connection_export  (<connected-to-sbus_decoder_channel_5_external_connection_export>),  //  sbus_decoder_channel_5_external_connection.export
		.sbus_decoder_channel_6_external_connection_export  (<connected-to-sbus_decoder_channel_6_external_connection_export>),  //  sbus_decoder_channel_6_external_connection.export
		.sbus_decoder_channel_7_external_connection_export  (<connected-to-sbus_decoder_channel_7_external_connection_export>),  //  sbus_decoder_channel_7_external_connection.export
		.sbus_decoder_channel_8_external_connection_export  (<connected-to-sbus_decoder_channel_8_external_connection_export>),  //  sbus_decoder_channel_8_external_connection.export
		.sbus_decoder_channel_9_external_connection_export  (<connected-to-sbus_decoder_channel_9_external_connection_export>),  //  sbus_decoder_channel_9_external_connection.export
		.sbus_decoder_reg_0_external_connection_export      (<connected-to-sbus_decoder_reg_0_external_connection_export>),      //      sbus_decoder_reg_0_external_connection.export
		.sbus_decoder_reg_10_external_connection_export     (<connected-to-sbus_decoder_reg_10_external_connection_export>),     //     sbus_decoder_reg_10_external_connection.export
		.sbus_decoder_reg_1_external_connection_export      (<connected-to-sbus_decoder_reg_1_external_connection_export>),      //      sbus_decoder_reg_1_external_connection.export
		.sbus_decoder_reg_2_external_connection_export      (<connected-to-sbus_decoder_reg_2_external_connection_export>),      //      sbus_decoder_reg_2_external_connection.export
		.sbus_decoder_reg_3_external_connection_export      (<connected-to-sbus_decoder_reg_3_external_connection_export>),      //      sbus_decoder_reg_3_external_connection.export
		.sbus_decoder_reg_4_external_connection_export      (<connected-to-sbus_decoder_reg_4_external_connection_export>),      //      sbus_decoder_reg_4_external_connection.export
		.sbus_decoder_reg_5_external_connection_export      (<connected-to-sbus_decoder_reg_5_external_connection_export>),      //      sbus_decoder_reg_5_external_connection.export
		.sbus_decoder_reg_6_external_connection_export      (<connected-to-sbus_decoder_reg_6_external_connection_export>),      //      sbus_decoder_reg_6_external_connection.export
		.sbus_decoder_reg_7_external_connection_export      (<connected-to-sbus_decoder_reg_7_external_connection_export>),      //      sbus_decoder_reg_7_external_connection.export
		.sbus_decoder_reg_8_external_connection_export      (<connected-to-sbus_decoder_reg_8_external_connection_export>),      //      sbus_decoder_reg_8_external_connection.export
		.sbus_decoder_reg_9_external_connection_export      (<connected-to-sbus_decoder_reg_9_external_connection_export>),      //      sbus_decoder_reg_9_external_connection.export
		.sdram_addr                                         (<connected-to-sdram_addr>),                                         //                                       sdram.addr
		.sdram_ba                                           (<connected-to-sdram_ba>),                                           //                                            .ba
		.sdram_cas_n                                        (<connected-to-sdram_cas_n>),                                        //                                            .cas_n
		.sdram_cke                                          (<connected-to-sdram_cke>),                                          //                                            .cke
		.sdram_cs_n                                         (<connected-to-sdram_cs_n>),                                         //                                            .cs_n
		.sdram_dq                                           (<connected-to-sdram_dq>),                                           //                                            .dq
		.sdram_dqm                                          (<connected-to-sdram_dqm>),                                          //                                            .dqm
		.sdram_ras_n                                        (<connected-to-sdram_ras_n>),                                        //                                            .ras_n
		.sdram_we_n                                         (<connected-to-sdram_we_n>),                                         //                                            .we_n
		.switches0_17_export                                (<connected-to-switches0_17_export>),                                //                                switches0_17.export
		.uart_0_external_connection_rxd                     (<connected-to-uart_0_external_connection_rxd>),                     //                  uart_0_external_connection.rxd
		.uart_0_external_connection_txd                     (<connected-to-uart_0_external_connection_txd>),                     //                                            .txd
		.sdram_clk_clk                                      (<connected-to-sdram_clk_clk>)                                       //                                   sdram_clk.clk
	);

