# TCL File Generated by Component Editor 20.1
# Thu Dec 03 11:07:34 PST 2020
# DO NOT MODIFY


# 
# slave_template "slave_template" v2.0
# JCJB 2020.12.03.11:07:34
# Parameterizable input/output component with an Avalon-MM slave port
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module slave_template
# 
set_module_property DESCRIPTION "Parameterizable input/output component with an Avalon-MM slave port"
set_module_property NAME slave_template
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Templates
set_module_property AUTHOR JCJB
set_module_property DISPLAY_NAME slave_template
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL slave_template
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property quartus_synth ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file slave_template.v VERILOG PATH slave_template.v TOP_LEVEL_FILE
add_fileset_file interrupt_logic.v VERILOG PATH interrupt_logic.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL slave_template
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file slave_template.v VERILOG PATH slave_template.v
add_fileset_file interrupt_logic.v VERILOG PATH interrupt_logic.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32 "Width of each input or output"
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME "Word Size"
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32}
set_parameter_property DATA_WIDTH DESCRIPTION "Width of each input or output"
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ENABLE_SYNC_SIGNALS INTEGER 0 "Output syncronization signals"
set_parameter_property ENABLE_SYNC_SIGNALS DEFAULT_VALUE 0
set_parameter_property ENABLE_SYNC_SIGNALS DISPLAY_NAME "Syncronization signals"
set_parameter_property ENABLE_SYNC_SIGNALS TYPE INTEGER
set_parameter_property ENABLE_SYNC_SIGNALS UNITS None
set_parameter_property ENABLE_SYNC_SIGNALS ALLOWED_RANGES {0:Disabled 1:Enabled}
set_parameter_property ENABLE_SYNC_SIGNALS DESCRIPTION "Output syncronization signals"
set_parameter_property ENABLE_SYNC_SIGNALS AFFECTS_GENERATION false
set_parameter_property ENABLE_SYNC_SIGNALS HDL_PARAMETER true
add_parameter MODE_0 INTEGER 2 "Set the read/write capabilites of the register pair 0"
set_parameter_property MODE_0 DEFAULT_VALUE 2
set_parameter_property MODE_0 DISPLAY_NAME "Register 0 capabilites"
set_parameter_property MODE_0 TYPE INTEGER
set_parameter_property MODE_0 UNITS None
set_parameter_property MODE_0 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_0 DESCRIPTION "Set the read/write capabilites of the register pair 0"
set_parameter_property MODE_0 AFFECTS_GENERATION false
set_parameter_property MODE_0 HDL_PARAMETER true
add_parameter MODE_1 INTEGER 2 "Set the read/write capabilites of the register pair 1"
set_parameter_property MODE_1 DEFAULT_VALUE 2
set_parameter_property MODE_1 DISPLAY_NAME "Register 1 capabilites"
set_parameter_property MODE_1 TYPE INTEGER
set_parameter_property MODE_1 UNITS None
set_parameter_property MODE_1 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_1 DESCRIPTION "Set the read/write capabilites of the register pair 1"
set_parameter_property MODE_1 AFFECTS_GENERATION false
set_parameter_property MODE_1 HDL_PARAMETER true
add_parameter MODE_2 INTEGER 2 "Set the read/write capabilites of the register pair 2"
set_parameter_property MODE_2 DEFAULT_VALUE 2
set_parameter_property MODE_2 DISPLAY_NAME "Register 2 capabilites"
set_parameter_property MODE_2 TYPE INTEGER
set_parameter_property MODE_2 UNITS None
set_parameter_property MODE_2 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_2 DESCRIPTION "Set the read/write capabilites of the register pair 2"
set_parameter_property MODE_2 AFFECTS_GENERATION false
set_parameter_property MODE_2 HDL_PARAMETER true
add_parameter MODE_3 INTEGER 2 "Set the read/write capabilites of the register pair 3"
set_parameter_property MODE_3 DEFAULT_VALUE 2
set_parameter_property MODE_3 DISPLAY_NAME "Register 3 capabilites"
set_parameter_property MODE_3 TYPE INTEGER
set_parameter_property MODE_3 UNITS None
set_parameter_property MODE_3 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_3 DESCRIPTION "Set the read/write capabilites of the register pair 3"
set_parameter_property MODE_3 AFFECTS_GENERATION false
set_parameter_property MODE_3 HDL_PARAMETER true
add_parameter MODE_4 INTEGER 2 "Set the read/write capabilites of the register pair 4"
set_parameter_property MODE_4 DEFAULT_VALUE 2
set_parameter_property MODE_4 DISPLAY_NAME "Register 4 capabilites"
set_parameter_property MODE_4 TYPE INTEGER
set_parameter_property MODE_4 UNITS None
set_parameter_property MODE_4 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_4 DESCRIPTION "Set the read/write capabilites of the register pair 4"
set_parameter_property MODE_4 AFFECTS_GENERATION false
set_parameter_property MODE_4 HDL_PARAMETER true
add_parameter MODE_5 INTEGER 2 "Set the read/write capabilites of the register pair 5"
set_parameter_property MODE_5 DEFAULT_VALUE 2
set_parameter_property MODE_5 DISPLAY_NAME "Register 5 capabilites"
set_parameter_property MODE_5 TYPE INTEGER
set_parameter_property MODE_5 UNITS None
set_parameter_property MODE_5 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_5 DESCRIPTION "Set the read/write capabilites of the register pair 5"
set_parameter_property MODE_5 AFFECTS_GENERATION false
set_parameter_property MODE_5 HDL_PARAMETER true
add_parameter MODE_6 INTEGER 2 "Set the read/write capabilites of the register pair 6"
set_parameter_property MODE_6 DEFAULT_VALUE 2
set_parameter_property MODE_6 DISPLAY_NAME "Register 6 capabilites"
set_parameter_property MODE_6 TYPE INTEGER
set_parameter_property MODE_6 UNITS None
set_parameter_property MODE_6 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_6 DESCRIPTION "Set the read/write capabilites of the register pair 6"
set_parameter_property MODE_6 AFFECTS_GENERATION false
set_parameter_property MODE_6 HDL_PARAMETER true
add_parameter MODE_7 INTEGER 2 "Set the read/write capabilites of the register pair 7"
set_parameter_property MODE_7 DEFAULT_VALUE 2
set_parameter_property MODE_7 DISPLAY_NAME "Register 7 capabilites"
set_parameter_property MODE_7 TYPE INTEGER
set_parameter_property MODE_7 UNITS None
set_parameter_property MODE_7 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_7 DESCRIPTION "Set the read/write capabilites of the register pair 7"
set_parameter_property MODE_7 AFFECTS_GENERATION false
set_parameter_property MODE_7 HDL_PARAMETER true
add_parameter MODE_8 INTEGER 2 "Set the read/write capabilites of the register pair 8"
set_parameter_property MODE_8 DEFAULT_VALUE 2
set_parameter_property MODE_8 DISPLAY_NAME "Register 8 capabilites"
set_parameter_property MODE_8 TYPE INTEGER
set_parameter_property MODE_8 UNITS None
set_parameter_property MODE_8 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_8 DESCRIPTION "Set the read/write capabilites of the register pair 8"
set_parameter_property MODE_8 AFFECTS_GENERATION false
set_parameter_property MODE_8 HDL_PARAMETER true
add_parameter MODE_9 INTEGER 2 "Set the read/write capabilites of the register pair 9"
set_parameter_property MODE_9 DEFAULT_VALUE 2
set_parameter_property MODE_9 DISPLAY_NAME "Register 9 capabilites"
set_parameter_property MODE_9 TYPE INTEGER
set_parameter_property MODE_9 UNITS None
set_parameter_property MODE_9 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_9 DESCRIPTION "Set the read/write capabilites of the register pair 9"
set_parameter_property MODE_9 AFFECTS_GENERATION false
set_parameter_property MODE_9 HDL_PARAMETER true
add_parameter MODE_10 INTEGER 2 "Set the read/write capabilites of the register pair 10"
set_parameter_property MODE_10 DEFAULT_VALUE 2
set_parameter_property MODE_10 DISPLAY_NAME "Register 10 capabilites"
set_parameter_property MODE_10 TYPE INTEGER
set_parameter_property MODE_10 UNITS None
set_parameter_property MODE_10 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_10 DESCRIPTION "Set the read/write capabilites of the register pair 10"
set_parameter_property MODE_10 AFFECTS_GENERATION false
set_parameter_property MODE_10 HDL_PARAMETER true
add_parameter MODE_11 INTEGER 2 "Set the read/write capabilites of the register pair 11"
set_parameter_property MODE_11 DEFAULT_VALUE 2
set_parameter_property MODE_11 DISPLAY_NAME "Register 11 capabilites"
set_parameter_property MODE_11 TYPE INTEGER
set_parameter_property MODE_11 UNITS None
set_parameter_property MODE_11 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_11 DESCRIPTION "Set the read/write capabilites of the register pair 11"
set_parameter_property MODE_11 AFFECTS_GENERATION false
set_parameter_property MODE_11 HDL_PARAMETER true
add_parameter MODE_12 INTEGER 2 "Set the read/write capabilites of the register pair 12"
set_parameter_property MODE_12 DEFAULT_VALUE 2
set_parameter_property MODE_12 DISPLAY_NAME "Register 12 capabilites"
set_parameter_property MODE_12 TYPE INTEGER
set_parameter_property MODE_12 UNITS None
set_parameter_property MODE_12 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_12 DESCRIPTION "Set the read/write capabilites of the register pair 12"
set_parameter_property MODE_12 AFFECTS_GENERATION false
set_parameter_property MODE_12 HDL_PARAMETER true
add_parameter MODE_13 INTEGER 2 "Set the read/write capabilites of the register pair 13"
set_parameter_property MODE_13 DEFAULT_VALUE 2
set_parameter_property MODE_13 DISPLAY_NAME "Register 13 capabilites"
set_parameter_property MODE_13 TYPE INTEGER
set_parameter_property MODE_13 UNITS None
set_parameter_property MODE_13 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_13 DESCRIPTION "Set the read/write capabilites of the register pair 13"
set_parameter_property MODE_13 AFFECTS_GENERATION false
set_parameter_property MODE_13 HDL_PARAMETER true
add_parameter MODE_14 INTEGER 2 "Set the read/write capabilites of the register pair 14"
set_parameter_property MODE_14 DEFAULT_VALUE 2
set_parameter_property MODE_14 DISPLAY_NAME "Register 14 capabilites"
set_parameter_property MODE_14 TYPE INTEGER
set_parameter_property MODE_14 UNITS None
set_parameter_property MODE_14 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_14 DESCRIPTION "Set the read/write capabilites of the register pair 14"
set_parameter_property MODE_14 AFFECTS_GENERATION false
set_parameter_property MODE_14 HDL_PARAMETER true
add_parameter MODE_15 INTEGER 2 "Set the read/write capabilites of the register pair 15"
set_parameter_property MODE_15 DEFAULT_VALUE 2
set_parameter_property MODE_15 DISPLAY_NAME "Register 15 capabilites"
set_parameter_property MODE_15 TYPE INTEGER
set_parameter_property MODE_15 UNITS None
set_parameter_property MODE_15 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_15 DESCRIPTION "Set the read/write capabilites of the register pair 15"
set_parameter_property MODE_15 AFFECTS_GENERATION false
set_parameter_property MODE_15 HDL_PARAMETER true
add_parameter IRQ_EN INTEGER 0 "Enable or disable the interrupt capabilities of input ports"
set_parameter_property IRQ_EN DEFAULT_VALUE 0
set_parameter_property IRQ_EN DISPLAY_NAME "Interrupt capabilities"
set_parameter_property IRQ_EN TYPE INTEGER
set_parameter_property IRQ_EN UNITS None
set_parameter_property IRQ_EN ALLOWED_RANGES {0:Disabled 1:Enabled}
set_parameter_property IRQ_EN DESCRIPTION "Enable or disable the interrupt capabilities of input ports"
set_parameter_property IRQ_EN AFFECTS_GENERATION false
set_parameter_property IRQ_EN HDL_PARAMETER true


# 
# display items
# 
add_display_item "" "Register File Properties" GROUP ""
add_display_item "Register File Properties" DATA_WIDTH PARAMETER ""
add_display_item "Register File Properties" ENABLE_SYNC_SIGNALS PARAMETER ""
add_display_item "" "Register File" GROUP ""
add_display_item "Register File" MODE_0 PARAMETER ""
add_display_item "Register File" MODE_1 PARAMETER ""
add_display_item "Register File" MODE_2 PARAMETER ""
add_display_item "Register File" MODE_3 PARAMETER ""
add_display_item "Register File" MODE_4 PARAMETER ""
add_display_item "Register File" MODE_5 PARAMETER ""
add_display_item "Register File" MODE_6 PARAMETER ""
add_display_item "Register File" MODE_7 PARAMETER ""
add_display_item "Register File" MODE_8 PARAMETER ""
add_display_item "Register File" MODE_9 PARAMETER ""
add_display_item "Register File" MODE_10 PARAMETER ""
add_display_item "Register File" MODE_11 PARAMETER ""
add_display_item "Register File" MODE_12 PARAMETER ""
add_display_item "Register File" MODE_13 PARAMETER ""
add_display_item "Register File" MODE_14 PARAMETER ""
add_display_item "Register File" MODE_15 PARAMETER ""
add_display_item "" Interrupt GROUP ""
add_display_item Interrupt IRQ_EN PARAMETER ""


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clk clk Input 1


# 
# connection point clock_reset_reset
# 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT
set_interface_property clock_reset_reset ENABLED true
set_interface_property clock_reset_reset EXPORT_OF ""
set_interface_property clock_reset_reset PORT_NAME_MAP ""
set_interface_property clock_reset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset_reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock_reset
set_interface_property s0 associatedReset clock_reset_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 3
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 slave_address address Input 9
add_interface_port s0 slave_read read Input 1
add_interface_port s0 slave_write write Input 1
add_interface_port s0 slave_readdata readdata Output DATA_WIDTH
add_interface_port s0 slave_writedata writedata Input DATA_WIDTH
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice false
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage false
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice false


# 
# connection point slv_irq
# 
add_interface slv_irq interrupt end
set_interface_property slv_irq associatedAddressablePoint s0
set_interface_property slv_irq associatedClock clock_reset
set_interface_property slv_irq associatedReset clock_reset_reset
set_interface_property slv_irq bridgedReceiverOffset ""
set_interface_property slv_irq bridgesToReceiver ""
set_interface_property slv_irq ENABLED true
set_interface_property slv_irq EXPORT_OF ""
set_interface_property slv_irq PORT_NAME_MAP ""
set_interface_property slv_irq CMSIS_SVD_VARIABLES ""
set_interface_property slv_irq SVD_ADDRESS_GROUP ""

add_interface_port slv_irq slave_irq irq Output 1


# 
# connection point user_interface
# 
add_interface user_interface conduit end
set_interface_property user_interface associatedClock clock_reset
set_interface_property user_interface associatedReset clock_reset_reset
set_interface_property user_interface ENABLED true
set_interface_property user_interface EXPORT_OF ""
set_interface_property user_interface PORT_NAME_MAP ""
set_interface_property user_interface CMSIS_SVD_VARIABLES ""
set_interface_property user_interface SVD_ADDRESS_GROUP ""

add_interface_port user_interface user_dataout_0 user_dataout_0_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_1 user_dataout_1_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_2 user_dataout_2_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_3 user_dataout_3_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_4 user_dataout_4_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_5 user_dataout_5_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_6 user_dataout_6_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_7 user_dataout_7_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_8 user_dataout_8_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_9 user_dataout_9_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_10 user_dataout_10_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_11 user_dataout_11_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_12 user_dataout_12_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_13 user_dataout_13_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_14 user_dataout_14_export Output DATA_WIDTH
add_interface_port user_interface user_dataout_15 user_dataout_15_export Output DATA_WIDTH
add_interface_port user_interface user_datain_0 user_datain_0_export Input DATA_WIDTH
add_interface_port user_interface user_datain_1 user_datain_1_export Input DATA_WIDTH
add_interface_port user_interface user_datain_2 user_datain_2_export Input DATA_WIDTH
add_interface_port user_interface user_datain_3 user_datain_3_export Input DATA_WIDTH
add_interface_port user_interface user_datain_4 user_datain_4_export Input DATA_WIDTH
add_interface_port user_interface user_datain_5 user_datain_5_export Input DATA_WIDTH
add_interface_port user_interface user_datain_6 user_datain_6_export Input DATA_WIDTH
add_interface_port user_interface user_datain_7 user_datain_7_export Input DATA_WIDTH
add_interface_port user_interface user_datain_8 user_datain_8_export Input DATA_WIDTH
add_interface_port user_interface user_datain_9 user_datain_9_export Input DATA_WIDTH
add_interface_port user_interface user_datain_10 user_datain_10_export Input DATA_WIDTH
add_interface_port user_interface user_datain_11 user_datain_11_export Input DATA_WIDTH
add_interface_port user_interface user_datain_12 user_datain_12_export Input DATA_WIDTH
add_interface_port user_interface user_datain_13 user_datain_13_export Input DATA_WIDTH
add_interface_port user_interface user_datain_14 user_datain_14_export Input DATA_WIDTH
add_interface_port user_interface user_datain_15 user_datain_15_export Input DATA_WIDTH
add_interface_port user_interface user_write user_write_export Output 1
add_interface_port user_interface user_read user_read_export Output 1
add_interface_port user_interface user_chipselect user_chipselect_export Output 16

