/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'ECE178_nios_20_1'
 * SOPC Builder design path: C:/Users/tasker/Projects/ECE178_nios_system_20_1/ECE178_nios_20_1.sopcinfo
 *
 * Generated: Tue Dec 08 02:51:38 PST 2020
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x08002820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x08002820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_NIOS2_GEN2


/*
 * GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_GPIO altera_avalon_pio
#define GPIO_BASE 0x8003210
#define GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define GPIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define GPIO_CAPTURE 0
#define GPIO_DATA_WIDTH 8
#define GPIO_DO_TEST_BENCH_WIRING 0
#define GPIO_DRIVEN_SIM_VALUE 0
#define GPIO_EDGE_TYPE "NONE"
#define GPIO_FREQ 50000000
#define GPIO_HAS_IN 0
#define GPIO_HAS_OUT 1
#define GPIO_HAS_TRI 0
#define GPIO_IRQ -1
#define GPIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define GPIO_IRQ_TYPE "NONE"
#define GPIO_NAME "/dev/GPIO"
#define GPIO_RESET_VALUE 0
#define GPIO_SPAN 16
#define GPIO_TYPE "altera_avalon_pio"


/*
 * High_Res_Timer configuration
 *
 */

#define ALT_MODULE_CLASS_High_Res_Timer altera_avalon_timer
#define HIGH_RES_TIMER_ALWAYS_RUN 0
#define HIGH_RES_TIMER_BASE 0x8003040
#define HIGH_RES_TIMER_COUNTER_SIZE 32
#define HIGH_RES_TIMER_FIXED_PERIOD 0
#define HIGH_RES_TIMER_FREQ 50000000
#define HIGH_RES_TIMER_IRQ 0
#define HIGH_RES_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define HIGH_RES_TIMER_LOAD_VALUE 49
#define HIGH_RES_TIMER_MULT 1.0E-6
#define HIGH_RES_TIMER_NAME "/dev/High_Res_Timer"
#define HIGH_RES_TIMER_PERIOD 1
#define HIGH_RES_TIMER_PERIOD_UNITS "us"
#define HIGH_RES_TIMER_RESET_OUTPUT 0
#define HIGH_RES_TIMER_SNAPSHOT 1
#define HIGH_RES_TIMER_SPAN 32
#define HIGH_RES_TIMER_TICKS_PER_SEC 1000000
#define HIGH_RES_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define HIGH_RES_TIMER_TYPE "altera_avalon_timer"


/*
 * KEYS configuration
 *
 */

#define ALT_MODULE_CLASS_KEYS altera_avalon_pio
#define KEYS_BASE 0x8003220
#define KEYS_BIT_CLEARING_EDGE_REGISTER 0
#define KEYS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYS_CAPTURE 1
#define KEYS_DATA_WIDTH 4
#define KEYS_DO_TEST_BENCH_WIRING 0
#define KEYS_DRIVEN_SIM_VALUE 0
#define KEYS_EDGE_TYPE "ANY"
#define KEYS_FREQ 50000000
#define KEYS_HAS_IN 1
#define KEYS_HAS_OUT 0
#define KEYS_HAS_TRI 0
#define KEYS_IRQ 2
#define KEYS_IRQ_INTERRUPT_CONTROLLER_ID 0
#define KEYS_IRQ_TYPE "LEVEL"
#define KEYS_NAME "/dev/KEYS"
#define KEYS_RESET_VALUE 0
#define KEYS_SPAN 16
#define KEYS_TYPE "altera_avalon_pio"


/*
 * LEDG configuration
 *
 */

#define ALT_MODULE_CLASS_LEDG altera_avalon_pio
#define LEDG_BASE 0x8003230
#define LEDG_BIT_CLEARING_EDGE_REGISTER 0
#define LEDG_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDG_CAPTURE 0
#define LEDG_DATA_WIDTH 9
#define LEDG_DO_TEST_BENCH_WIRING 0
#define LEDG_DRIVEN_SIM_VALUE 0
#define LEDG_EDGE_TYPE "NONE"
#define LEDG_FREQ 50000000
#define LEDG_HAS_IN 0
#define LEDG_HAS_OUT 1
#define LEDG_HAS_TRI 0
#define LEDG_IRQ -1
#define LEDG_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDG_IRQ_TYPE "NONE"
#define LEDG_NAME "/dev/LEDG"
#define LEDG_RESET_VALUE 0
#define LEDG_SPAN 16
#define LEDG_TYPE "altera_avalon_pio"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x8003280
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x8003280
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x8003280
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "ECE178_nios_20_1"


/*
 * System_Timer configuration
 *
 */

#define ALT_MODULE_CLASS_System_Timer altera_avalon_timer
#define SYSTEM_TIMER_ALWAYS_RUN 0
#define SYSTEM_TIMER_BASE 0x8003020
#define SYSTEM_TIMER_COUNTER_SIZE 32
#define SYSTEM_TIMER_FIXED_PERIOD 0
#define SYSTEM_TIMER_FREQ 50000000
#define SYSTEM_TIMER_IRQ 1
#define SYSTEM_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYSTEM_TIMER_LOAD_VALUE 49999
#define SYSTEM_TIMER_MULT 0.001
#define SYSTEM_TIMER_NAME "/dev/System_Timer"
#define SYSTEM_TIMER_PERIOD 1
#define SYSTEM_TIMER_PERIOD_UNITS "ms"
#define SYSTEM_TIMER_RESET_OUTPUT 0
#define SYSTEM_TIMER_SNAPSHOT 1
#define SYSTEM_TIMER_SPAN 32
#define SYSTEM_TIMER_TICKS_PER_SEC 1000
#define SYSTEM_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYSTEM_TIMER_TYPE "altera_avalon_timer"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK SYSTEM_TIMER
#define ALT_TIMESTAMP_CLK HIGH_RES_TIMER


/*
 * hex0_3 configuration
 *
 */

#define ALT_MODULE_CLASS_hex0_3 altera_avalon_pio
#define HEX0_3_BASE 0x8003270
#define HEX0_3_BIT_CLEARING_EDGE_REGISTER 0
#define HEX0_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX0_3_CAPTURE 0
#define HEX0_3_DATA_WIDTH 32
#define HEX0_3_DO_TEST_BENCH_WIRING 0
#define HEX0_3_DRIVEN_SIM_VALUE 0
#define HEX0_3_EDGE_TYPE "NONE"
#define HEX0_3_FREQ 50000000
#define HEX0_3_HAS_IN 0
#define HEX0_3_HAS_OUT 1
#define HEX0_3_HAS_TRI 0
#define HEX0_3_IRQ -1
#define HEX0_3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX0_3_IRQ_TYPE "NONE"
#define HEX0_3_NAME "/dev/hex0_3"
#define HEX0_3_RESET_VALUE 0
#define HEX0_3_SPAN 16
#define HEX0_3_TYPE "altera_avalon_pio"


/*
 * hex4_7 configuration
 *
 */

#define ALT_MODULE_CLASS_hex4_7 altera_avalon_pio
#define HEX4_7_BASE 0x8003260
#define HEX4_7_BIT_CLEARING_EDGE_REGISTER 0
#define HEX4_7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX4_7_CAPTURE 0
#define HEX4_7_DATA_WIDTH 32
#define HEX4_7_DO_TEST_BENCH_WIRING 0
#define HEX4_7_DRIVEN_SIM_VALUE 0
#define HEX4_7_EDGE_TYPE "NONE"
#define HEX4_7_FREQ 50000000
#define HEX4_7_HAS_IN 0
#define HEX4_7_HAS_OUT 1
#define HEX4_7_HAS_TRI 0
#define HEX4_7_IRQ -1
#define HEX4_7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX4_7_IRQ_TYPE "NONE"
#define HEX4_7_NAME "/dev/hex4_7"
#define HEX4_7_RESET_VALUE 0
#define HEX4_7_SPAN 16
#define HEX4_7_TYPE "altera_avalon_pio"


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x8003280
#define JTAG_UART_0_IRQ 5
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * ledr configuration
 *
 */

#define ALT_MODULE_CLASS_ledr altera_avalon_pio
#define LEDR_BASE 0x8003240
#define LEDR_BIT_CLEARING_EDGE_REGISTER 0
#define LEDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDR_CAPTURE 0
#define LEDR_DATA_WIDTH 18
#define LEDR_DO_TEST_BENCH_WIRING 0
#define LEDR_DRIVEN_SIM_VALUE 0
#define LEDR_EDGE_TYPE "NONE"
#define LEDR_FREQ 50000000
#define LEDR_HAS_IN 0
#define LEDR_HAS_OUT 1
#define LEDR_HAS_TRI 0
#define LEDR_IRQ -1
#define LEDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDR_IRQ_TYPE "NONE"
#define LEDR_NAME "/dev/ledr"
#define LEDR_RESET_VALUE 0
#define LEDR_SPAN 16
#define LEDR_TYPE "altera_avalon_pio"


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x8001000
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "ECE178_nios_20_1_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 4096
#define ONCHIP_MEMORY2_0_SPAN 4096
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * sbus_decoder_channel_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_0 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_0_BASE 0x8003160
#define SBUS_DECODER_CHANNEL_0_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_0_CAPTURE 0
#define SBUS_DECODER_CHANNEL_0_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_0_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_0_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_0_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_0_FREQ 50000000
#define SBUS_DECODER_CHANNEL_0_HAS_IN 1
#define SBUS_DECODER_CHANNEL_0_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_0_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_0_IRQ -1
#define SBUS_DECODER_CHANNEL_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_0_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_0_NAME "/dev/sbus_decoder_channel_0"
#define SBUS_DECODER_CHANNEL_0_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_0_SPAN 16
#define SBUS_DECODER_CHANNEL_0_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_1 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_1 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_1_BASE 0x8003150
#define SBUS_DECODER_CHANNEL_1_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_1_CAPTURE 0
#define SBUS_DECODER_CHANNEL_1_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_1_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_1_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_1_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_1_FREQ 50000000
#define SBUS_DECODER_CHANNEL_1_HAS_IN 1
#define SBUS_DECODER_CHANNEL_1_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_1_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_1_IRQ -1
#define SBUS_DECODER_CHANNEL_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_1_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_1_NAME "/dev/sbus_decoder_channel_1"
#define SBUS_DECODER_CHANNEL_1_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_1_SPAN 16
#define SBUS_DECODER_CHANNEL_1_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_10 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_10 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_10_BASE 0x80030c0
#define SBUS_DECODER_CHANNEL_10_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_10_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_10_CAPTURE 0
#define SBUS_DECODER_CHANNEL_10_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_10_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_10_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_10_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_10_FREQ 50000000
#define SBUS_DECODER_CHANNEL_10_HAS_IN 1
#define SBUS_DECODER_CHANNEL_10_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_10_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_10_IRQ -1
#define SBUS_DECODER_CHANNEL_10_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_10_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_10_NAME "/dev/sbus_decoder_channel_10"
#define SBUS_DECODER_CHANNEL_10_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_10_SPAN 16
#define SBUS_DECODER_CHANNEL_10_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_11 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_11 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_11_BASE 0x80030b0
#define SBUS_DECODER_CHANNEL_11_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_11_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_11_CAPTURE 0
#define SBUS_DECODER_CHANNEL_11_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_11_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_11_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_11_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_11_FREQ 50000000
#define SBUS_DECODER_CHANNEL_11_HAS_IN 1
#define SBUS_DECODER_CHANNEL_11_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_11_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_11_IRQ -1
#define SBUS_DECODER_CHANNEL_11_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_11_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_11_NAME "/dev/sbus_decoder_channel_11"
#define SBUS_DECODER_CHANNEL_11_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_11_SPAN 16
#define SBUS_DECODER_CHANNEL_11_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_12 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_12 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_12_BASE 0x80030a0
#define SBUS_DECODER_CHANNEL_12_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_12_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_12_CAPTURE 0
#define SBUS_DECODER_CHANNEL_12_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_12_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_12_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_12_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_12_FREQ 50000000
#define SBUS_DECODER_CHANNEL_12_HAS_IN 1
#define SBUS_DECODER_CHANNEL_12_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_12_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_12_IRQ -1
#define SBUS_DECODER_CHANNEL_12_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_12_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_12_NAME "/dev/sbus_decoder_channel_12"
#define SBUS_DECODER_CHANNEL_12_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_12_SPAN 16
#define SBUS_DECODER_CHANNEL_12_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_13 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_13 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_13_BASE 0x8003090
#define SBUS_DECODER_CHANNEL_13_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_13_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_13_CAPTURE 0
#define SBUS_DECODER_CHANNEL_13_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_13_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_13_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_13_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_13_FREQ 50000000
#define SBUS_DECODER_CHANNEL_13_HAS_IN 1
#define SBUS_DECODER_CHANNEL_13_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_13_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_13_IRQ -1
#define SBUS_DECODER_CHANNEL_13_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_13_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_13_NAME "/dev/sbus_decoder_channel_13"
#define SBUS_DECODER_CHANNEL_13_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_13_SPAN 16
#define SBUS_DECODER_CHANNEL_13_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_14 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_14 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_14_BASE 0x8003080
#define SBUS_DECODER_CHANNEL_14_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_14_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_14_CAPTURE 0
#define SBUS_DECODER_CHANNEL_14_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_14_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_14_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_14_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_14_FREQ 50000000
#define SBUS_DECODER_CHANNEL_14_HAS_IN 1
#define SBUS_DECODER_CHANNEL_14_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_14_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_14_IRQ -1
#define SBUS_DECODER_CHANNEL_14_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_14_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_14_NAME "/dev/sbus_decoder_channel_14"
#define SBUS_DECODER_CHANNEL_14_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_14_SPAN 16
#define SBUS_DECODER_CHANNEL_14_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_15 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_15 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_15_BASE 0x8003070
#define SBUS_DECODER_CHANNEL_15_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_15_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_15_CAPTURE 0
#define SBUS_DECODER_CHANNEL_15_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_15_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_15_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_15_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_15_FREQ 50000000
#define SBUS_DECODER_CHANNEL_15_HAS_IN 1
#define SBUS_DECODER_CHANNEL_15_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_15_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_15_IRQ -1
#define SBUS_DECODER_CHANNEL_15_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_15_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_15_NAME "/dev/sbus_decoder_channel_15"
#define SBUS_DECODER_CHANNEL_15_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_15_SPAN 16
#define SBUS_DECODER_CHANNEL_15_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_2 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_2 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_2_BASE 0x8003140
#define SBUS_DECODER_CHANNEL_2_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_2_CAPTURE 0
#define SBUS_DECODER_CHANNEL_2_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_2_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_2_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_2_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_2_FREQ 50000000
#define SBUS_DECODER_CHANNEL_2_HAS_IN 1
#define SBUS_DECODER_CHANNEL_2_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_2_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_2_IRQ -1
#define SBUS_DECODER_CHANNEL_2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_2_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_2_NAME "/dev/sbus_decoder_channel_2"
#define SBUS_DECODER_CHANNEL_2_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_2_SPAN 16
#define SBUS_DECODER_CHANNEL_2_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_3 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_3 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_3_BASE 0x8003130
#define SBUS_DECODER_CHANNEL_3_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_3_CAPTURE 0
#define SBUS_DECODER_CHANNEL_3_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_3_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_3_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_3_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_3_FREQ 50000000
#define SBUS_DECODER_CHANNEL_3_HAS_IN 1
#define SBUS_DECODER_CHANNEL_3_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_3_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_3_IRQ -1
#define SBUS_DECODER_CHANNEL_3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_3_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_3_NAME "/dev/sbus_decoder_channel_3"
#define SBUS_DECODER_CHANNEL_3_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_3_SPAN 16
#define SBUS_DECODER_CHANNEL_3_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_4 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_4 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_4_BASE 0x8003120
#define SBUS_DECODER_CHANNEL_4_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_4_CAPTURE 0
#define SBUS_DECODER_CHANNEL_4_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_4_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_4_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_4_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_4_FREQ 50000000
#define SBUS_DECODER_CHANNEL_4_HAS_IN 1
#define SBUS_DECODER_CHANNEL_4_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_4_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_4_IRQ -1
#define SBUS_DECODER_CHANNEL_4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_4_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_4_NAME "/dev/sbus_decoder_channel_4"
#define SBUS_DECODER_CHANNEL_4_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_4_SPAN 16
#define SBUS_DECODER_CHANNEL_4_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_5 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_5 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_5_BASE 0x8003110
#define SBUS_DECODER_CHANNEL_5_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_5_CAPTURE 0
#define SBUS_DECODER_CHANNEL_5_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_5_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_5_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_5_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_5_FREQ 50000000
#define SBUS_DECODER_CHANNEL_5_HAS_IN 1
#define SBUS_DECODER_CHANNEL_5_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_5_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_5_IRQ -1
#define SBUS_DECODER_CHANNEL_5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_5_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_5_NAME "/dev/sbus_decoder_channel_5"
#define SBUS_DECODER_CHANNEL_5_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_5_SPAN 16
#define SBUS_DECODER_CHANNEL_5_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_6 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_6 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_6_BASE 0x8003100
#define SBUS_DECODER_CHANNEL_6_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_6_CAPTURE 0
#define SBUS_DECODER_CHANNEL_6_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_6_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_6_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_6_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_6_FREQ 50000000
#define SBUS_DECODER_CHANNEL_6_HAS_IN 1
#define SBUS_DECODER_CHANNEL_6_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_6_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_6_IRQ -1
#define SBUS_DECODER_CHANNEL_6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_6_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_6_NAME "/dev/sbus_decoder_channel_6"
#define SBUS_DECODER_CHANNEL_6_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_6_SPAN 16
#define SBUS_DECODER_CHANNEL_6_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_7 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_7 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_7_BASE 0x80030f0
#define SBUS_DECODER_CHANNEL_7_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_7_CAPTURE 0
#define SBUS_DECODER_CHANNEL_7_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_7_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_7_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_7_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_7_FREQ 50000000
#define SBUS_DECODER_CHANNEL_7_HAS_IN 1
#define SBUS_DECODER_CHANNEL_7_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_7_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_7_IRQ -1
#define SBUS_DECODER_CHANNEL_7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_7_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_7_NAME "/dev/sbus_decoder_channel_7"
#define SBUS_DECODER_CHANNEL_7_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_7_SPAN 16
#define SBUS_DECODER_CHANNEL_7_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_8 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_8 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_8_BASE 0x80030e0
#define SBUS_DECODER_CHANNEL_8_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_8_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_8_CAPTURE 0
#define SBUS_DECODER_CHANNEL_8_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_8_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_8_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_8_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_8_FREQ 50000000
#define SBUS_DECODER_CHANNEL_8_HAS_IN 1
#define SBUS_DECODER_CHANNEL_8_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_8_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_8_IRQ -1
#define SBUS_DECODER_CHANNEL_8_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_8_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_8_NAME "/dev/sbus_decoder_channel_8"
#define SBUS_DECODER_CHANNEL_8_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_8_SPAN 16
#define SBUS_DECODER_CHANNEL_8_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_channel_9 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_channel_9 altera_avalon_pio
#define SBUS_DECODER_CHANNEL_9_BASE 0x80030d0
#define SBUS_DECODER_CHANNEL_9_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_CHANNEL_9_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_CHANNEL_9_CAPTURE 0
#define SBUS_DECODER_CHANNEL_9_DATA_WIDTH 11
#define SBUS_DECODER_CHANNEL_9_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_CHANNEL_9_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_CHANNEL_9_EDGE_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_9_FREQ 50000000
#define SBUS_DECODER_CHANNEL_9_HAS_IN 1
#define SBUS_DECODER_CHANNEL_9_HAS_OUT 0
#define SBUS_DECODER_CHANNEL_9_HAS_TRI 0
#define SBUS_DECODER_CHANNEL_9_IRQ -1
#define SBUS_DECODER_CHANNEL_9_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_CHANNEL_9_IRQ_TYPE "NONE"
#define SBUS_DECODER_CHANNEL_9_NAME "/dev/sbus_decoder_channel_9"
#define SBUS_DECODER_CHANNEL_9_RESET_VALUE 0
#define SBUS_DECODER_CHANNEL_9_SPAN 16
#define SBUS_DECODER_CHANNEL_9_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_0 altera_avalon_pio
#define SBUS_DECODER_REG_0_BASE 0x8003200
#define SBUS_DECODER_REG_0_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_0_CAPTURE 0
#define SBUS_DECODER_REG_0_DATA_WIDTH 16
#define SBUS_DECODER_REG_0_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_0_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_0_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_0_FREQ 50000000
#define SBUS_DECODER_REG_0_HAS_IN 0
#define SBUS_DECODER_REG_0_HAS_OUT 1
#define SBUS_DECODER_REG_0_HAS_TRI 0
#define SBUS_DECODER_REG_0_IRQ -1
#define SBUS_DECODER_REG_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_0_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_0_NAME "/dev/sbus_decoder_reg_0"
#define SBUS_DECODER_REG_0_RESET_VALUE 0
#define SBUS_DECODER_REG_0_SPAN 16
#define SBUS_DECODER_REG_0_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_1 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_1 altera_avalon_pio
#define SBUS_DECODER_REG_1_BASE 0x80031f0
#define SBUS_DECODER_REG_1_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_1_CAPTURE 0
#define SBUS_DECODER_REG_1_DATA_WIDTH 16
#define SBUS_DECODER_REG_1_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_1_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_1_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_1_FREQ 50000000
#define SBUS_DECODER_REG_1_HAS_IN 0
#define SBUS_DECODER_REG_1_HAS_OUT 1
#define SBUS_DECODER_REG_1_HAS_TRI 0
#define SBUS_DECODER_REG_1_IRQ -1
#define SBUS_DECODER_REG_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_1_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_1_NAME "/dev/sbus_decoder_reg_1"
#define SBUS_DECODER_REG_1_RESET_VALUE 0
#define SBUS_DECODER_REG_1_SPAN 16
#define SBUS_DECODER_REG_1_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_10 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_10 altera_avalon_pio
#define SBUS_DECODER_REG_10_BASE 0x8003060
#define SBUS_DECODER_REG_10_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_10_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_10_CAPTURE 0
#define SBUS_DECODER_REG_10_DATA_WIDTH 16
#define SBUS_DECODER_REG_10_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_10_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_10_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_10_FREQ 50000000
#define SBUS_DECODER_REG_10_HAS_IN 0
#define SBUS_DECODER_REG_10_HAS_OUT 1
#define SBUS_DECODER_REG_10_HAS_TRI 0
#define SBUS_DECODER_REG_10_IRQ -1
#define SBUS_DECODER_REG_10_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_10_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_10_NAME "/dev/sbus_decoder_reg_10"
#define SBUS_DECODER_REG_10_RESET_VALUE 0
#define SBUS_DECODER_REG_10_SPAN 16
#define SBUS_DECODER_REG_10_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_2 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_2 altera_avalon_pio
#define SBUS_DECODER_REG_2_BASE 0x80031e0
#define SBUS_DECODER_REG_2_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_2_CAPTURE 0
#define SBUS_DECODER_REG_2_DATA_WIDTH 16
#define SBUS_DECODER_REG_2_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_2_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_2_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_2_FREQ 50000000
#define SBUS_DECODER_REG_2_HAS_IN 0
#define SBUS_DECODER_REG_2_HAS_OUT 1
#define SBUS_DECODER_REG_2_HAS_TRI 0
#define SBUS_DECODER_REG_2_IRQ -1
#define SBUS_DECODER_REG_2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_2_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_2_NAME "/dev/sbus_decoder_reg_2"
#define SBUS_DECODER_REG_2_RESET_VALUE 0
#define SBUS_DECODER_REG_2_SPAN 16
#define SBUS_DECODER_REG_2_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_3 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_3 altera_avalon_pio
#define SBUS_DECODER_REG_3_BASE 0x80031d0
#define SBUS_DECODER_REG_3_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_3_CAPTURE 0
#define SBUS_DECODER_REG_3_DATA_WIDTH 16
#define SBUS_DECODER_REG_3_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_3_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_3_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_3_FREQ 50000000
#define SBUS_DECODER_REG_3_HAS_IN 0
#define SBUS_DECODER_REG_3_HAS_OUT 1
#define SBUS_DECODER_REG_3_HAS_TRI 0
#define SBUS_DECODER_REG_3_IRQ -1
#define SBUS_DECODER_REG_3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_3_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_3_NAME "/dev/sbus_decoder_reg_3"
#define SBUS_DECODER_REG_3_RESET_VALUE 0
#define SBUS_DECODER_REG_3_SPAN 16
#define SBUS_DECODER_REG_3_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_4 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_4 altera_avalon_pio
#define SBUS_DECODER_REG_4_BASE 0x80031c0
#define SBUS_DECODER_REG_4_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_4_CAPTURE 0
#define SBUS_DECODER_REG_4_DATA_WIDTH 16
#define SBUS_DECODER_REG_4_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_4_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_4_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_4_FREQ 50000000
#define SBUS_DECODER_REG_4_HAS_IN 0
#define SBUS_DECODER_REG_4_HAS_OUT 1
#define SBUS_DECODER_REG_4_HAS_TRI 0
#define SBUS_DECODER_REG_4_IRQ -1
#define SBUS_DECODER_REG_4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_4_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_4_NAME "/dev/sbus_decoder_reg_4"
#define SBUS_DECODER_REG_4_RESET_VALUE 0
#define SBUS_DECODER_REG_4_SPAN 16
#define SBUS_DECODER_REG_4_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_5 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_5 altera_avalon_pio
#define SBUS_DECODER_REG_5_BASE 0x80031b0
#define SBUS_DECODER_REG_5_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_5_CAPTURE 0
#define SBUS_DECODER_REG_5_DATA_WIDTH 16
#define SBUS_DECODER_REG_5_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_5_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_5_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_5_FREQ 50000000
#define SBUS_DECODER_REG_5_HAS_IN 0
#define SBUS_DECODER_REG_5_HAS_OUT 1
#define SBUS_DECODER_REG_5_HAS_TRI 0
#define SBUS_DECODER_REG_5_IRQ -1
#define SBUS_DECODER_REG_5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_5_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_5_NAME "/dev/sbus_decoder_reg_5"
#define SBUS_DECODER_REG_5_RESET_VALUE 0
#define SBUS_DECODER_REG_5_SPAN 16
#define SBUS_DECODER_REG_5_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_6 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_6 altera_avalon_pio
#define SBUS_DECODER_REG_6_BASE 0x80031a0
#define SBUS_DECODER_REG_6_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_6_CAPTURE 0
#define SBUS_DECODER_REG_6_DATA_WIDTH 16
#define SBUS_DECODER_REG_6_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_6_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_6_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_6_FREQ 50000000
#define SBUS_DECODER_REG_6_HAS_IN 0
#define SBUS_DECODER_REG_6_HAS_OUT 1
#define SBUS_DECODER_REG_6_HAS_TRI 0
#define SBUS_DECODER_REG_6_IRQ -1
#define SBUS_DECODER_REG_6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_6_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_6_NAME "/dev/sbus_decoder_reg_6"
#define SBUS_DECODER_REG_6_RESET_VALUE 0
#define SBUS_DECODER_REG_6_SPAN 16
#define SBUS_DECODER_REG_6_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_7 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_7 altera_avalon_pio
#define SBUS_DECODER_REG_7_BASE 0x8003190
#define SBUS_DECODER_REG_7_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_7_CAPTURE 0
#define SBUS_DECODER_REG_7_DATA_WIDTH 16
#define SBUS_DECODER_REG_7_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_7_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_7_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_7_FREQ 50000000
#define SBUS_DECODER_REG_7_HAS_IN 0
#define SBUS_DECODER_REG_7_HAS_OUT 1
#define SBUS_DECODER_REG_7_HAS_TRI 0
#define SBUS_DECODER_REG_7_IRQ -1
#define SBUS_DECODER_REG_7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_7_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_7_NAME "/dev/sbus_decoder_reg_7"
#define SBUS_DECODER_REG_7_RESET_VALUE 0
#define SBUS_DECODER_REG_7_SPAN 16
#define SBUS_DECODER_REG_7_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_8 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_8 altera_avalon_pio
#define SBUS_DECODER_REG_8_BASE 0x8003180
#define SBUS_DECODER_REG_8_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_8_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_8_CAPTURE 0
#define SBUS_DECODER_REG_8_DATA_WIDTH 16
#define SBUS_DECODER_REG_8_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_8_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_8_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_8_FREQ 50000000
#define SBUS_DECODER_REG_8_HAS_IN 0
#define SBUS_DECODER_REG_8_HAS_OUT 1
#define SBUS_DECODER_REG_8_HAS_TRI 0
#define SBUS_DECODER_REG_8_IRQ -1
#define SBUS_DECODER_REG_8_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_8_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_8_NAME "/dev/sbus_decoder_reg_8"
#define SBUS_DECODER_REG_8_RESET_VALUE 0
#define SBUS_DECODER_REG_8_SPAN 16
#define SBUS_DECODER_REG_8_TYPE "altera_avalon_pio"


/*
 * sbus_decoder_reg_9 configuration
 *
 */

#define ALT_MODULE_CLASS_sbus_decoder_reg_9 altera_avalon_pio
#define SBUS_DECODER_REG_9_BASE 0x8003170
#define SBUS_DECODER_REG_9_BIT_CLEARING_EDGE_REGISTER 0
#define SBUS_DECODER_REG_9_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SBUS_DECODER_REG_9_CAPTURE 0
#define SBUS_DECODER_REG_9_DATA_WIDTH 16
#define SBUS_DECODER_REG_9_DO_TEST_BENCH_WIRING 0
#define SBUS_DECODER_REG_9_DRIVEN_SIM_VALUE 0
#define SBUS_DECODER_REG_9_EDGE_TYPE "NONE"
#define SBUS_DECODER_REG_9_FREQ 50000000
#define SBUS_DECODER_REG_9_HAS_IN 0
#define SBUS_DECODER_REG_9_HAS_OUT 1
#define SBUS_DECODER_REG_9_HAS_TRI 0
#define SBUS_DECODER_REG_9_IRQ -1
#define SBUS_DECODER_REG_9_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SBUS_DECODER_REG_9_IRQ_TYPE "NONE"
#define SBUS_DECODER_REG_9_NAME "/dev/sbus_decoder_reg_9"
#define SBUS_DECODER_REG_9_RESET_VALUE 0
#define SBUS_DECODER_REG_9_SPAN 16
#define SBUS_DECODER_REG_9_TYPE "altera_avalon_pio"


/*
 * sdram_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_0 altera_avalon_new_sdram_controller
#define SDRAM_0_BASE 0x0
#define SDRAM_0_CAS_LATENCY 3
#define SDRAM_0_CONTENTS_INFO
#define SDRAM_0_INIT_NOP_DELAY 0.0
#define SDRAM_0_INIT_REFRESH_COMMANDS 2
#define SDRAM_0_IRQ -1
#define SDRAM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_0_IS_INITIALIZED 1
#define SDRAM_0_NAME "/dev/sdram_0"
#define SDRAM_0_POWERUP_DELAY 200.0
#define SDRAM_0_REFRESH_PERIOD 7.8125
#define SDRAM_0_REGISTER_DATA_IN 1
#define SDRAM_0_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_0_SDRAM_BANK_WIDTH 2
#define SDRAM_0_SDRAM_COL_WIDTH 10
#define SDRAM_0_SDRAM_DATA_WIDTH 32
#define SDRAM_0_SDRAM_NUM_BANKS 4
#define SDRAM_0_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_0_SDRAM_ROW_WIDTH 13
#define SDRAM_0_SHARED_DATA 0
#define SDRAM_0_SIM_MODEL_BASE 0
#define SDRAM_0_SPAN 134217728
#define SDRAM_0_STARVATION_INDICATOR 0
#define SDRAM_0_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_0_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_0_T_AC 5.5
#define SDRAM_0_T_MRD 3
#define SDRAM_0_T_RCD 20.0
#define SDRAM_0_T_RFC 70.0
#define SDRAM_0_T_RP 20.0
#define SDRAM_0_T_WR 14.0


/*
 * switches0_17 configuration
 *
 */

#define ALT_MODULE_CLASS_switches0_17 altera_avalon_pio
#define SWITCHES0_17_BASE 0x8003250
#define SWITCHES0_17_BIT_CLEARING_EDGE_REGISTER 0
#define SWITCHES0_17_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SWITCHES0_17_CAPTURE 0
#define SWITCHES0_17_DATA_WIDTH 18
#define SWITCHES0_17_DO_TEST_BENCH_WIRING 0
#define SWITCHES0_17_DRIVEN_SIM_VALUE 0
#define SWITCHES0_17_EDGE_TYPE "NONE"
#define SWITCHES0_17_FREQ 50000000
#define SWITCHES0_17_HAS_IN 1
#define SWITCHES0_17_HAS_OUT 0
#define SWITCHES0_17_HAS_TRI 0
#define SWITCHES0_17_IRQ -1
#define SWITCHES0_17_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SWITCHES0_17_IRQ_TYPE "NONE"
#define SWITCHES0_17_NAME "/dev/switches0_17"
#define SWITCHES0_17_RESET_VALUE 0
#define SWITCHES0_17_SPAN 16
#define SWITCHES0_17_TYPE "altera_avalon_pio"


/*
 * uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_uart_0 altera_avalon_uart
#define UART_0_BASE 0x8003000
#define UART_0_BAUD 115200
#define UART_0_DATA_BITS 8
#define UART_0_FIXED_BAUD 0
#define UART_0_FREQ 50000000
#define UART_0_IRQ 4
#define UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define UART_0_NAME "/dev/uart_0"
#define UART_0_PARITY 'E'
#define UART_0_SIM_CHAR_STREAM ""
#define UART_0_SIM_TRUE_BAUD 0
#define UART_0_SPAN 32
#define UART_0_STOP_BITS 2
#define UART_0_SYNC_REG_DEPTH 2
#define UART_0_TYPE "altera_avalon_uart"
#define UART_0_USE_CTS_RTS 0
#define UART_0_USE_EOP_REGISTER 0

#endif /* __SYSTEM_H_ */
